name: llm_judge
channels:
  - conda-forge
dependencies:
  - openai
  - pypdf2
  - python-dotenv
  - python=3.11
  - google-genai
  - requests
  - conda-lock
prefix: /Users/skysheng/miniforge3/envs/llm_judge
