name: llm_judge
channels:
  - conda-forge
platforms:
  - linux-64
  - osx-arm64
  - win-64
dependencies:
  - openai
  - pypdf2
  - python-dotenv
  - python=3.11
  - google-genai
  - requests
  - conda-lock
  - anthropic
  - pip
  - pip:
    - ollama
